Repository SwingTheVine/Wplace-BlueMarble, pull requests merged in 2025-08, with the labels that each got.

#27 Minimize Window Feature & Pixel Counting System
  dist/BlueMarble.user.css
  dist/BlueMarble.user.js
  src/Template.js
  src/main.js
  src/overlay.css
  src/templateManager.js
Labels: enhancement, good report

#65 Fixed issues with Issue templates...
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/PULL_REQUEST_TEMPLATE/pull-request.yml
Labels: bug, documentation

#64 fix map loading after migration from openfreemap to custom map backend
  src/main.js
Labels: bug, good report

#62 Simplify installation instructions with one-click install links
  .github/workflows/build.yml
  docs/README.md
Labels: documentation

#49 Change transform easing to 0s
  src/overlay.css
Labels: enhancement

#59 Added a translucent gray checkerboard render for #deface
  src/Template.js
Labels: enhancement

#106 Minor fix: links
  .github/workflows/build.yml
  docs/README.md
Labels: documentation, in-progress

#124 Fix some issues with the README
  .eslintignore
  .github/workflows/pr-branch-check.yml
  .prettierignore
  dist/BlueMarble.user.css
  dist/BlueMarble.user.js
  docs/README.md
  package.json
  src/BlueMarble.meta.js
  src/Template.js
  src/overlay.css
Labels: documentation

#140 Update Wplace status badge
  docs/README.md
Labels: documentation

#191 Color filtering & telemetry
  .github/workflows/build.yml
  .github/workflows/pr-branch-check.yml
  dist/BlueMarble.user.css
  dist/BlueMarble.user.css.map.json
  dist/BlueMarble.user.js
  docs/CONTRIBUTING.md
  docs/CREDITS.md
  docs/README.md
  docs/SECURITY.md
  jsdoc.json
  package-lock.json
  package.json
  src/BlueMarble.meta.js
  src/Template.js
  src/apiManager.js
  src/main.js
  src/overlay.css
  src/templateManager.js
  src/utils.js
Labels: bug, documentation, enhancement

#266 Updated Color Filter to Include Invalid ("Other") Pixels
  .github/workflows/pr-branch-check.yml
  dist/BlueMarble.user.js
  docs/CONTRIBUTING.md
  docs/README.md
  package-lock.json
  package.json
  src/BlueMarble.meta.js
  src/Template.js
  src/main.js
  src/templateManager.js
Labels: bug, documentation, enhancement

#253 docs: extend FAQ and update menu/overlay descriptions
  docs/README.md
Labels: documentation, good report

#332 Fix image source link in README.md
  docs/README.md
Labels: documentation
